# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e24759a90024ce12eb7900b2596197070200de64c7a6cfc637ce16c87e28cf58d456d375612bc3cef4098119ba29cb2da90eb2a6b56572e2d252bdefee5ad4a

test:
  secret_key_base: 7d6b4ac6530b160142247a166f9c8c91a1725b1d1e97df317cc0601f8e2ee38644025d06ffe31028d1f7c02a1cc64a6bb763c86bec443e845dbd17a3c22b47f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
